run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - node_modules

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - misspell
    - gofmt
    - goimports
    - gosec
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
  gosec:
    excludes:
      - G307 # Deferring unsafe method "Close" on type "*os.File"
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec