services:
  alerting-db:
    image: postgres:16
    container_name: alerting-db
    network_mode: "host"
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER:-alerting}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-alerting}
      POSTGRES_DB: ${DB_NAME:-alerting}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # Uncomment these lines to enable SSL in production
      # - ./ssl/server.crt:/var/lib/postgresql/server.crt:ro
      # - ./ssl/server.key:/var/lib/postgresql/server.key:ro
      # command: >
      #   -c ssl=on
      #   -c ssl_cert_file=/var/lib/postgresql/server.crt
      #   -c ssl_key_file=/var/lib/postgresql/server.key

  api:
    depends_on:
      - alerting-db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alerting-api
    volumes:
      - .:/app
    ports:
      - '${PORT:-8080}:${PORT:-8080}'
    env_file:
      - .env
    command: go run main.go

volumes:
  postgres-data:
    name: alerting-postgres-data
    driver: local
    # This makes the volume "anonymous" so it will be automatically removed when the container is removed
    external: false
