services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alerting-api
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=alerting
      - DB_PASSWORD=alerting
      - DB_NAME=alerting
      - DB_SSL_MODE=disable
      - API_PASSWORD=c3c7ecb61de9998c5009545b707c28fe
      - LOG_LEVEL=debug
      - LOG_FORMAT=console
    depends_on:
      alerting-db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  alerting-db:
    image: postgres:16
    container_name: alerting-db
    network_mode: "host"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=alerting
      - POSTGRES_PASSWORD=alerting
      - POSTGRES_DB=alerting
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alerting"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    name: alerting-postgres-data
    driver: local
    # This makes the volume "anonymous" so it will be automatically removed when the container is removed
    external: false