version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: alerting-postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-alerting}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d/migrations
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alerting-api
    volumes:
      - .:/app
    ports:
      - '${PORT:-8080}:8080'
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: go run main.go

volumes:
  postgres-data:
    name: alerting-postgres-data
